# Generated by Django 6.0.2 on 2026-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='cloud_layer',
            new_name='cloud_layers',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='precipitation',
            new_name='precipitation_last_hour',
        ),
        migrations.RemoveField(
            model_name='environmentaldata',
            name='tide_stage',
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='astronomical_twilight_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='astronomical_twilight_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='atmospheric_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='civil_twilight_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='civil_twilight_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='conductivity_flags',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='current_bin_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='current_direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='current_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='day_length',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='nautical_twilight_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='nautical_twilight_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='raw_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='solar_noon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_flags',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_quality_indicator',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_standard_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='water_temperature_flags',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
