# Generated by Django 6.0.2 on 2026-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cloud_layer_environmentaldata_cloud_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaldata',
            name='age_days',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='atmospheric_text_1hr_prior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='atmospheric_text_3hr_prior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='cloud_cover_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='cloud_cover_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='cloud_layers_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='cloud_layers_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='dewpoint_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='dewpoint_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='illumination',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_blood_moon',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_eclipse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_waxing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moon_phase',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_phases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='phase_angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='precipitation_last_hour_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='precipitation_last_hour_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='pressure_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='pressure_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='raw_message_1hr_prior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='raw_message_3hr_prior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='relative_humidity_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='relative_humidity_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='temperature_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='temperature_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_flags_1hr_prior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_flags_3hr_prior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_flags_6hr_prior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_height_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_height_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_height_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_quality_indicator_1hr_prior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_quality_indicator_3hr_prior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_quality_indicator_6hr_prior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_standard_deviation_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_standard_deviation_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='tide_standard_deviation_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='visibility_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='visibility_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_direction_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_direction_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_gust_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_gust_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_speed_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='wind_speed_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='source_type',
            field=models.CharField(choices=[('USER', 'User Submission'), ('API', 'External API'), ('SENSOR', 'Sensor Device')], default='USER', max_length=20),
        ),
    ]
