# Generated by Django 6.0.2 on 2026-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_environmentaldata_age_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaldata',
            name='age_days_1hr_prior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='age_days_3hr_prior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='age_days_6hr_prior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='distance_km_1hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='distance_km_3hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='distance_km_6hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='illumination_1hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='illumination_3hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='illumination_6hr_prior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_blood_moon_1hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_blood_moon_3hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_blood_moon_6hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_eclipse_1hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_eclipse_3hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_eclipse_6hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_waxing_1hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_waxing_3hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_waxing_6hr_prior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moon_phase_1hr_prior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moon_phase_3hr_prior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moon_phase_6hr_prior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonrise_1hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonrise_3hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonrise_6hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonset_1hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonset_3hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='moonset_6hr_prior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_phases_1hr_prior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_phases_3hr_prior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_phases_6hr_prior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='phase_angle_1hr_prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='phase_angle_3hr_prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='phase_angle_6hr_prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
