# Generated by Django 6.0.2 on 2026-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_environmentaldata_age_days_1hr_prior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaldata',
            name='age_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='age_days_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='age_days_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='age_days_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='distance_km_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='distance_km_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='distance_km_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='illumination',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='illumination_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='illumination_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='illumination_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='phase_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='phase_angle_1hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='phase_angle_3hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='phase_angle_6hr_prior',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
