# Generated by Django 6.0.2 on 2026-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_environmentaldata_age_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentaldata',
            name='next_phases',
        ),
        migrations.RemoveField(
            model_name='environmentaldata',
            name='next_phases_1hr_prior',
        ),
        migrations.RemoveField(
            model_name='environmentaldata',
            name='next_phases_3hr_prior',
        ),
        migrations.RemoveField(
            model_name='environmentaldata',
            name='next_phases_6hr_prior',
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_first_quarter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_full_moon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_last_quarter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='next_new_moon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
